spring:
  application:
    name: website

  datasource:
    url: ${DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      schema: ${DATABASE_SCHEMA}
